<?php

namespace ContainerV7c7yfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAuthTokenCommandHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Core\Application\Command\AuthToken\CreateAuthToken\CreateAuthTokenCommandHandler' shared autowired service.
     *
     * @return \App\Core\Application\Command\AuthToken\CreateAuthToken\CreateAuthTokenCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Core/Application/Command/AuthToken/CreateAuthToken/CreateAuthTokenCommandHandler.php';

        return $container->privates['App\\Core\\Application\\Command\\AuthToken\\CreateAuthToken\\CreateAuthTokenCommandHandler'] = new \App\Core\Application\Command\AuthToken\CreateAuthToken\CreateAuthTokenCommandHandler(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), ($container->privates['App\\Core\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')));
    }
}
