<?php

namespace ContainerV7c7yfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserCommandHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Core\Application\Command\User\CreateUser\CreateUserCommandHandler' shared autowired service.
     *
     * @return \App\Core\Application\Command\User\CreateUser\CreateUserCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Core/Application/Command/User/CreateUser/CreateUserCommandHandler.php';

        return $container->privates['App\\Core\\Application\\Command\\User\\CreateUser\\CreateUserCommandHandler'] = new \App\Core\Application\Command\User\CreateUser\CreateUserCommandHandler(($container->privates['security.encoder_factory.generic'] ?? $container->load('getSecurity_EncoderFactory_GenericService')), ($container->privates['App\\Core\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
