<?php

namespace ContainerV7c7yfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand_Bus_Messenger_HandlersLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'command.bus.messenger.handlers_locator' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlersLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        return $container->privates['command.bus.messenger.handlers_locator'] = new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\Core\\Application\\Command\\AuthToken\\CreateAuthToken\\CreateAuthTokenCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.7ekgP1M'] ?? $container->load('get_Messenger_HandlerDescriptor_7ekgP1MService'));
        }, 1), 'App\\Core\\Application\\Command\\Parcels\\CreateParcel\\CreateParcelCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.lnAf.gJ'] ?? $container->load('get_Messenger_HandlerDescriptor_LnAf_GJService'));
        }, 1), 'App\\Core\\Application\\Command\\User\\CreateUser\\CreateUserCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.9ktM88I'] ?? $container->load('get_Messenger_HandlerDescriptor_9ktM88IService'));
        }, 1)]);
    }
}
