<?php

namespace ContainerV7c7yfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Doctrine\DomainEventSubscriber' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Doctrine\DomainEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Doctrine/DomainEventSubscriber.php';

        return $container->privates['App\\Shared\\Infrastructure\\Doctrine\\DomainEventSubscriber'] = new \App\Shared\Infrastructure\Doctrine\DomainEventSubscriber(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
    }
}
