<?php

namespace ContainerV7c7yfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializer_NameConverter_CamelCaseToSnakeCaseService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'serializer.name_converter.camel_case_to_snake_case' shared service.
     *
     * @return \Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/NameConverter/NameConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/NameConverter/CamelCaseToSnakeCaseNameConverter.php';

        return $container->privates['serializer.name_converter.camel_case_to_snake_case'] = new \Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter();
    }
}
