<?php

namespace ContainerRzn4OgO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_MessengerDebugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.messenger_debug' shared service.
     *
     * @return \Symfony\Component\Messenger\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Command/DebugCommand.php';

        $container->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['command.bus' => ['App\\Core\\Application\\Command\\AuthToken\\CreateAuthToken\\CreateAuthTokenCommand' => [0 => [0 => 'App\\Core\\Application\\Command\\AuthToken\\CreateAuthToken\\CreateAuthTokenCommandHandler', 1 => []]], 'App\\Core\\Application\\Command\\Parcels\\CreateParcel\\CreateParcelCommand' => [0 => [0 => 'App\\Core\\Application\\Command\\Parcels\\CreateParcel\\CreateParcelCommandHandler', 1 => []]], 'App\\Core\\Application\\Command\\User\\CreateUser\\CreateUserCommand' => [0 => [0 => 'App\\Core\\Application\\Command\\User\\CreateUser\\CreateUserCommandHandler', 1 => []]]], 'query.bus' => ['App\\Core\\Application\\Query\\Parcel\\GetParcel\\GetParcelQuery' => [0 => [0 => 'App\\Core\\Application\\Query\\Parcel\\GetParcel\\GetParcelQueryHandler', 1 => []]]], 'event.bus' => []]);

        $instance->setName('debug:messenger');

        return $instance;
    }
}
