<?php

namespace ContainerPPcUifC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateParcelCommandHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Core\Application\Command\Parcels\CreateParcel\CreateParcelCommandHandler' shared autowired service.
     *
     * @return \App\Core\Application\Command\Parcels\CreateParcel\CreateParcelCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Core/Application/Command/Parcels/CreateParcel/CreateParcelCommandHandler.php';

        return $container->privates['App\\Core\\Application\\Command\\Parcels\\CreateParcel\\CreateParcelCommandHandler'] = new \App\Core\Application\Command\Parcels\CreateParcel\CreateParcelCommandHandler(($container->privates['App\\Core\\Infrastructure\\Repository\\ParcelRepository'] ?? $container->load('getParcelRepositoryService')), ($container->privates['App\\Core\\Infrastructure\\Security\\UserFetcher'] ?? $container->load('getUserFetcherService')));
    }
}
