<?php

namespace ContainerPPcUifC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetParcelQueryHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Core\Application\Query\Parcel\GetParcel\GetParcelQueryHandler' shared autowired service.
     *
     * @return \App\Core\Application\Query\Parcel\GetParcel\GetParcelQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Core/Application/Query/Parcel/GetParcel/GetParcelQueryHandler.php';

        return $container->privates['App\\Core\\Application\\Query\\Parcel\\GetParcel\\GetParcelQueryHandler'] = new \App\Core\Application\Query\Parcel\GetParcel\GetParcelQueryHandler(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Core\\Infrastructure\\Repository\\ParcelRepository'] ?? $container->load('getParcelRepositoryService')));
    }
}
