<?php

namespace ContainerPPcUifC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFetcherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Core\Infrastructure\Security\UserFetcher' shared autowired service.
     *
     * @return \App\Core\Infrastructure\Security\UserFetcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Core/Domain/Model/User/UserFetcherInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Core/Infrastructure/Security/UserFetcher.php';

        return $container->privates['App\\Core\\Infrastructure\\Security\\UserFetcher'] = new \App\Core\Infrastructure\Security\UserFetcher(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
