<?php

namespace Container6xuKu0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAuthTokenActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Core\Ports\Rest\AuthToken\CreateAuthTokenAction' shared autowired service.
     *
     * @return \App\Core\Ports\Rest\AuthToken\CreateAuthTokenAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/HandleTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Core/Ports/Rest/AuthToken/CreateAuthTokenAction.php';

        return $container->services['App\\Core\\Ports\\Rest\\AuthToken\\CreateAuthTokenAction'] = new \App\Core\Ports\Rest\AuthToken\CreateAuthTokenAction(($container->privates['command.bus'] ?? $container->load('getCommand_BusService')));
    }
}
