<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV7c7yfD\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV7c7yfD/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerV7c7yfD.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerV7c7yfD\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerV7c7yfD\App_KernelTestDebugContainer([
    'container.build_hash' => 'V7c7yfD',
    'container.build_id' => 'cfc70b14',
    'container.build_time' => 1601044889,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV7c7yfD');
