<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xuKu0d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xuKu0d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6xuKu0d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6xuKu0d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6xuKu0d\App_KernelDevDebugContainer([
    'container.build_hash' => '6xuKu0d',
    'container.build_id' => '60d1d217',
    'container.build_time' => 1601048949,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xuKu0d');
