<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'login_check' => [[], ['_controller' => 'App\\Core\\Ports\\Rest\\AuthToken\\CreateAuthTokenAction'], [], [['text', '/api/login_check']], [], []],
    'api_get_parcel' => [['trackingId'], ['_controller' => 'App\\Core\\Ports\\Rest\\Parcel\\GetParcelAction'], [], [['variable', '/', '[^/]++', 'trackingId', true], ['text', '/api/parcels']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
